# Generated by Django 6.0.7 on 2026-07-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('date', models.DateTimeField()),
                ('event_type', models.CharField(choices=[('MEETING', 'Meeting'), ('SOCIAL', 'Social'), ('LAUNCH', 'Launch'), ('FUNDRAISER', 'Fundraiser'), ('WORKSHOP', 'Workshop')], default='MEETING', max_length=26)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
