# Generated by Django 6.0.7 on 2026-07-18 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, help_text='Cover photo shown on cards and at the top of the article.', null=True, upload_to='articles/covers/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(help_text='Markdown supported. Upload photos below and paste the snippet where you want them to appear.'),
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='articles/photos/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='events.article')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
