# Generated by Django 6.0.7 on 2026-07-18 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_article_image_alter_article_body_articleimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(help_text='Markdown supported. Upload photos below and paste the snippet where you want them to appear. Add {: width="300" } right after an image to resize it, e.g. ![caption](url){: width="300" }.'),
        ),
    ]
