# Generated by Django 6.0.7 on 2026-07-18 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Component',
        ),
    ]
