# Generated by Django 6.0.7 on 2026-07-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officerhistory',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
