# Generated by Django 6.0.7 on 2026-07-18 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('membership', '0002_alter_officerhistory_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requests_approved', to='membership.member', verbose_name='Reviewed by'),
        ),
    ]
